---
- hosts: dsal_routers
  remote_user: root
  tasks:
    #    - name: setup 10GbE
    #      copy: src=setupnetwork.sh dest=/root/setupnetwork.sh mode=0755
    #    - name: install 10GbE settings
    #      shell: /root/setupnetwork.sh
    - name: install router dependencies
      shell: yum install -y java-1.8.0-openjdk gcc cmake libuuid-devel openssl-devel swig python-devel gcc-c++ cmake make wget patch git

    - file: path=/root/qpid-dispatch-src state=absent
    - file: path=/root/qpid-proton-src state=absent
    - file: path=/root/dispatch_build state=absent
    - file: path=/root/proton_build state=absent

      #- name: download qpid proton master
      #- raw: wget http://github.com/apache/qpid-proton/archive/master.tar.gz -O qpid-proton.tar.gz
    
    - name: download dispatch code
      shell: git clone http://github.com/lulf/qpid-dispatch qpid-dispatch-src && cd qpid-dispatch-src && git checkout dsal_scaling
      #- name: build and install proton
      #- raw: mkdir -p /root/qpid-proton-src /root/proton_build && tar -xzf /root/qpid-proton.tar.gz -C /root/qpid-proton-src --strip-components 1 && cd /root/proton_build && cmake -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_CPP=OFF -DCMAKE_BUILD_TYPE=RelWithDebInfo -DBUILD_PERL=OFF -DBUILD_RUBY=OFF -DBUILD_JAVA=OFF -DBUILD_GO=OFF -DBUILD_JAVASCRIPT=OFF -DBUILD_PHP=OFF /root/qpid-proton-src && make && make install
    - name: build and install dispatch
      shell: mkdir /root/dispatch_build && cd /root/dispatch_build && cmake -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_DOCS=OFF -DCMAKE_BUILD_TYPE=RelWithDebInfo -DUSE_MEMORY_POOL=OFF -DCONSOLE_INSTALL=OFF /root/qpid-dispatch-src && make && make install
    - name: router startup script
      copy: src=start_router.sh dest=/root/start_router.sh mode=0755
    - name: add systemd service file
      copy: src=router.service dest=/usr/lib/systemd/system/dispatchrouter.service

